In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [3]:
x =np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [4]:
y=np.zeros((3, 3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [5]:
a=x+y
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [6]:
print(x.dtype)

float64


In [7]:
print(x.ndim)

2


In [8]:
print(x.shape)

(3, 3)


In [9]:
print(x.size)

9


In [10]:
print(type(x))

<class 'numpy.ndarray'>


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [11]:
w=np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [12]:
z=np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [29]:
r=w.reshape(2,3)
newArray=np.vstack((r, z))
newArray

array([[11, 12, 13],
       [14, 15, 16],
       [ 1,  2,  3]])

In [30]:
newArray2=np.column_stack((w,z))
newArray2

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [15]:
for item in newArray.flat:
    print(item)

11
12
13
14
15
16
1
2
3


In [16]:
for item in newArray2.flat:
    print(item)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [18]:
newArray.transpose()

array([[11, 14,  1],
       [12, 15,  2],
       [13, 16,  3]])

In [19]:
newArray2.transpose()

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [31]:
newArray=newArray-1
newArray

array([[10, 11, 12],
       [13, 14, 15],
       [ 0,  1,  2]])

In [32]:
newArray2=newArray2-1
newArray2

array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [33]:
newArray.min()

0

In [34]:
newArray2.min()

0

In [37]:
newArray.max()

15

In [38]:
newArray2.max()

15

## Q#12: Print the first row of "newArray" using indexing.

In [39]:
newArray[0]

array([10, 11, 12])

In [40]:
newArray2[0]

array([10, 11,  0])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [42]:
newArray[0][2]

12

In [43]:
newArray2[1][0]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [44]:
newArray[1:,0]

array([13,  0])

In [45]:
newArray2[0:2,1:]

array([[11,  0],
       [13,  1]])

## Q#15: Change the shape of "newArray" to (9,1).

In [46]:
newArray.reshape(9,1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [ 0],
       [ 1],
       [ 2]])

In [47]:
newArray2.reshape(9,1)

array([[10],
       [11],
       [ 0],
       [12],
       [13],
       [ 1],
       [14],
       [15],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [ ]:
can not because is 9 items cannot convert to 3,2

# Well Done 🎉